version: '3.4'

services:
  sb:
    platform: linux/amd64
    container_name: sb
    image: drymek/sb:latest
    entrypoint: /entrypoint.sh
    build:
      context: ../../
      dockerfile: deployments/Dockerfile
      target: builder
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./../../:/go/src/sb
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - NEWRELIC_CONFIG_LICENSE=${NEWRELIC_CONFIG_LICENSE}

  database:
    image: postgres
    container_name: sb_database
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sb
      POSTGRES_DB: sb
    volumes:
      - ../../database/postgres:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"