name: SpaceBook CI
on:
  push:
    branches: [ main ]

jobs:
  main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: postgres
          options: --detach --volume ${{ github.workspace }}/database/postgres:/docker-entrypoint-initdb.d --env POSTGRES_USER=sb --env POSTGRES_PASSWORD=password --env POSTGRES_DB=sb --publish 5432:5432
          run: docker-entrypoint.sh postgres
          
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: go test $(go list ./... | grep -v /vendor/) -v

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployments/Dockerfile
          push: true
          tags: drymek/spacebook:latest
