name: SpaceBook CI
on:
  pull_request:
    branches: [ main ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: postgres
          options: --volume ${{ github.workspace }}/database/postgres:/docker-entrypoint-initdb.d --env POSTGRES_USER=sb --env POSTGRES_PASSWORD=password --env POSTGRES_DB=sb --publish 5432:5432

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: go test $(go list ./... | grep -v /vendor/) -v
